export const dashboard = [
    {
        path: "reservations.index",
        name: "Reservation and Booking",
        icon: "fa fa-calendar-days",
        parent: false,
        children: [],
    },
    {
        path: "repairs.index",
        name: "Schedule a Repair",
        icon: "fa fa-screwdriver-wrench",
        parent: false,
        children: [],
    },
    {
        path: "bills-utilities.index",
        name: "Bills",
        icon: "fas fa-file-invoice",
        parent: false,
        children: [],
    },
    {
        path: null,
        name: "Rent / Admin Fees",
        icon: "fa fa-house",
        parent: false,
        children: [],
    },
    {
        path: "announcements.index",
        name: "Events / Announcements",
        icon: "fa fa-scroll",
        parent: false,
        children: [],
    },
    {
        path: "events.index",
        name: "Calendar Events",
        icon: "fa fa-calendar-day",
        parent: false,
        children: [],
    },
    // {
    //     path: null,
    //     name: "Document Records",
    //     icon: "fa fa-file",
    //     parent: false,
    //     children: [],
    // },
    {
        path: null,
        name: "Messages",
        icon: "fa fa-message",
        parent: false,
        children: [],
    },
    {
        path: "logbooks.index",
        name: "Visitor Logbook",
        icon: "fa fa-users",
        parent: false,
        children: [],
    },
    {
        path: "documents.index",
        name: "Request of Documents",
        icon: "fa fa-file-lines",
        parent: false,
        children: [],
    },
];
